fieldLayouts:
  95d61b16-0584-4218-9907-a13e81034802:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 2826630c-36ae-4d2f-b76b-a6de75f28c09
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: categories
name: Categories
siteSettings:
  fb333ff1-b85e-4828-a457-6cab943930a7:
    hasUrls: true
    template: null
    uriFormat: 'categories/{slug}'
structure:
  maxLevels: 2
  uid: 57d68f03-c0d4-42c8-b3e2-f69309250c51
