fieldLayouts:
  ccd91a8e-e601-405e-aced-c20f2e79fb42:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 0197d204-86da-410f-a382-331f210595fd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9c96fc99-3a5e-4e18-9685-55cf88ec9c5e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: naves
name: Naves
siteSettings:
  fb333ff1-b85e-4828-a457-6cab943930a7:
    hasUrls: true
    template: null
    uriFormat: 'naves/{slug}'
structure:
  maxLevels: null
  uid: f505bcdd-fd4d-4312-9075-a38cd146e2c9
