fieldLayouts:
  e095ae36-9426-471e-b7d4-f2bf492c4685:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: newTestamentCategories
name: 'New Testament Categories'
siteSettings:
  fb333ff1-b85e-4828-a457-6cab943930a7:
    hasUrls: true
    template: null
    uriFormat: 'new-testament-categories/{slug}'
structure:
  maxLevels: null
  uid: 066ede3c-1f10-4ddf-8846-48f71eade7c4
