fieldLayouts:
  214a61a0-a970-4ee5-87e8-39d0d5deeea2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: oldTestamentCategories
name: 'Old Testament Categories'
siteSettings:
  fb333ff1-b85e-4828-a457-6cab943930a7:
    hasUrls: true
    template: null
    uriFormat: 'old-testament-categories/{slug}'
structure:
  maxLevels: null
  uid: 94b48e56-0422-415f-bda1-ad61bc375a2b
