contentColumnType: integer(10)
fieldGroup: 3b8c4a76-5cb9-4076-a28e-19ad6bf3aa62
handle: eastonsBibleDictionaryOldId
instructions: ''
name: 'Easton''s Bible Dictionary Old Id'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  previewCurrency: ''
  previewFormat: none
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
