contentColumnType: integer(10)
fieldGroup: 24fe87af-1a5b-40ce-b43e-6ce00a4329de
handle: hitchcocksBibleDictionaryOldId
instructions: ''
name: 'Hitchcock''s Bible Dictionary Old Id'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  previewCurrency: ''
  previewFormat: none
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
