contentColumnType: integer(10)
fieldGroup: 0581820f-d1ac-4307-876b-a9496846209e
handle: kingJamesVersionVerse
instructions: ''
name: Verse
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
