contentColumnType: integer(10)
fieldGroup: 3d959c78-a072-4637-8649-1a437491f2d7
handle: linksOldId
instructions: ''
name: 'links old id'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  previewCurrency: ''
  previewFormat: none
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
