contentColumnType: string
fieldGroup: 3d959c78-a072-4637-8649-1a437491f2d7
handle: linksCategory
instructions: ''
name: 'Links Category'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:d05b69b1-4665-47bf-9de7-caa50c534947'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
