contentColumnType: text
fieldGroup: 6b74c67e-f7b4-462e-b79c-32992bcc2875
handle: navesAddenda
instructions: ''
name: Addenda
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
