contentColumnType: text
fieldGroup: 5e47b1b6-5afc-4cad-b71d-896915884491
handle: smithsBibleDictionaryWordStatus
instructions: ''
name: 'Smith''s Bible Dictionary Word Status'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
