contentColumnType: integer(10)
fieldGroup: 52bed830-b7aa-4b77-b4d5-e6f665579542
handle: studyBibleVerseNumber
instructions: ''
name: 'study bible verse number'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: ''
  previewCurrency: ''
  previewFormat: none
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
