dateModified: 1603121368
email:
  fromEmail: nikolay@networklocal.net
  fromName: 'Bible History'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 2.1.2
system:
  edition: solo
  live: false
  name: 'Bible History'
  retryDuration: null
  schemaVersion: 3.5.13
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
