fieldLayouts:
  970c4771-f904-4d70-ba57-1b03b99ffbf5:
    tabs:
      -
        elements:
          -
            fieldUid: 3cc7ba10-449c-4e0f-87a3-992787b337d2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48d473af-60e4-40a0-bf88-75edf5f86dd0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 14c1456a-a8dd-455f-953e-820c38af32a0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: globalSeo
name: 'SEO Default'
