enableVersioning: true
handle: jerusalem
name: Jerusalem
propagationMethod: all
siteSettings:
  fb333ff1-b85e-4828-a457-6cab943930a7:
    enabledByDefault: true
    hasUrls: true
    template: common_pages/_entry
    uriFormat: 'jerusalem/{slug}'
type: channel
