enableVersioning: true
handle: navesTopicalBible
name: 'Nave''s Topical Bible'
propagationMethod: all
siteSettings:
  fb333ff1-b85e-4828-a457-6cab943930a7:
    enabledByDefault: true
    hasUrls: true
    template: dictionaries/_entry
    uriFormat: 'naves/{slug[:1]}/{slug}'
type: channel
