enableVersioning: true
handle: navesTopicalBibleSingle
name: 'Nave''s Topical Bible Single'
propagationMethod: all
siteSettings:
  fb333ff1-b85e-4828-a457-6cab943930a7:
    enabledByDefault: true
    hasUrls: true
    template: dictionaries/index
    uriFormat: naves
type: single
