enableVersioning: true
handle: theHighPriesthood
name: 'The High Priesthood'
propagationMethod: all
siteSettings:
  fb333ff1-b85e-4828-a457-6cab943930a7:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'highpriests/{slug}'
type: channel
