enableVersioning: true
handle: theTaxCollectors
name: 'The Tax Collectors'
propagationMethod: all
siteSettings:
  fb333ff1-b85e-4828-a457-6cab943930a7:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'taxcollectors/{slug}'
type: channel
